/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface MonthlyTaskStats {
  'completedDays' : bigint,
  'taskTitle' : string,
  'totalDays' : bigint,
  'taskId' : string,
}
export interface StreakInfo {
  'longestStreak' : bigint,
  'currentStreak' : bigint,
}
export interface Task {
  'id' : string,
  'repeatDays' : Array<bigint>,
  'title' : string,
  'repeatType' : { 'Weekly' : null } |
    { 'Daily' : null } |
    { 'Custom' : null },
  'endDate' : [] | [string],
  'repeatInterval' : bigint,
  'createdAt' : bigint,
  'description' : string,
  'isActive' : boolean,
  'timeOfDay' : string,
  'startDate' : string,
}
export interface TaskCompletion {
  'completedAt' : bigint,
  'completionDate' : string,
  'taskId' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WeeklyStats {
  'total' : bigint,
  'date' : string,
  'completed' : bigint,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createTask' : ActorMethod<
    [
      string,
      string,
      string,
      { 'Weekly' : null } |
        { 'Daily' : null } |
        { 'Custom' : null },
      Array<bigint>,
      bigint,
      string,
      [] | [string],
    ],
    Task
  >,
  'deleteTask' : ActorMethod<[string], { 'ok' : boolean } | { 'err' : string }>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCompletionsForDate' : ActorMethod<[string], Array<TaskCompletion>>,
  'getCompletionsForRange' : ActorMethod<
    [string, string],
    Array<TaskCompletion>
  >,
  'getMonthlyTaskStats' : ActorMethod<[], Array<MonthlyTaskStats>>,
  'getStreakInfo' : ActorMethod<[], StreakInfo>,
  'getTasks' : ActorMethod<[], Array<Task>>,
  'getTasksForDate' : ActorMethod<[string], Array<Task>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWeeklyStats' : ActorMethod<[], Array<WeeklyStats>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markTaskComplete' : ActorMethod<
    [string, string],
    { 'ok' : TaskCompletion } |
      { 'err' : string }
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'unmarkTaskComplete' : ActorMethod<
    [string, string],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'updateTask' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      { 'Weekly' : null } |
        { 'Daily' : null } |
        { 'Custom' : null },
      Array<bigint>,
      bigint,
      string,
      [] | [string],
    ],
    { 'ok' : Task } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];