/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Task = IDL.Record({
  'id' : IDL.Text,
  'repeatDays' : IDL.Vec(IDL.Nat),
  'title' : IDL.Text,
  'repeatType' : IDL.Variant({
    'Weekly' : IDL.Null,
    'Daily' : IDL.Null,
    'Custom' : IDL.Null,
  }),
  'endDate' : IDL.Opt(IDL.Text),
  'repeatInterval' : IDL.Nat,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'timeOfDay' : IDL.Text,
  'startDate' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const TaskCompletion = IDL.Record({
  'completedAt' : IDL.Int,
  'completionDate' : IDL.Text,
  'taskId' : IDL.Text,
});
export const MonthlyTaskStats = IDL.Record({
  'completedDays' : IDL.Nat,
  'taskTitle' : IDL.Text,
  'totalDays' : IDL.Nat,
  'taskId' : IDL.Text,
});
export const StreakInfo = IDL.Record({
  'longestStreak' : IDL.Nat,
  'currentStreak' : IDL.Nat,
});
export const WeeklyStats = IDL.Record({
  'total' : IDL.Nat,
  'date' : IDL.Text,
  'completed' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createTask' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Variant({
          'Weekly' : IDL.Null,
          'Daily' : IDL.Null,
          'Custom' : IDL.Null,
        }),
        IDL.Vec(IDL.Nat),
        IDL.Nat,
        IDL.Text,
        IDL.Opt(IDL.Text),
      ],
      [Task],
      [],
    ),
  'deleteTask' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCompletionsForDate' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(TaskCompletion)],
      ['query'],
    ),
  'getCompletionsForRange' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(TaskCompletion)],
      ['query'],
    ),
  'getMonthlyTaskStats' : IDL.Func([], [IDL.Vec(MonthlyTaskStats)], ['query']),
  'getStreakInfo' : IDL.Func([], [StreakInfo], ['query']),
  'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getTasksForDate' : IDL.Func([IDL.Text], [IDL.Vec(Task)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWeeklyStats' : IDL.Func([], [IDL.Vec(WeeklyStats)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markTaskComplete' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : TaskCompletion, 'err' : IDL.Text })],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'unmarkTaskComplete' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'updateTask' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Variant({
          'Weekly' : IDL.Null,
          'Daily' : IDL.Null,
          'Custom' : IDL.Null,
        }),
        IDL.Vec(IDL.Nat),
        IDL.Nat,
        IDL.Text,
        IDL.Opt(IDL.Text),
      ],
      [IDL.Variant({ 'ok' : Task, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Task = IDL.Record({
    'id' : IDL.Text,
    'repeatDays' : IDL.Vec(IDL.Nat),
    'title' : IDL.Text,
    'repeatType' : IDL.Variant({
      'Weekly' : IDL.Null,
      'Daily' : IDL.Null,
      'Custom' : IDL.Null,
    }),
    'endDate' : IDL.Opt(IDL.Text),
    'repeatInterval' : IDL.Nat,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'timeOfDay' : IDL.Text,
    'startDate' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const TaskCompletion = IDL.Record({
    'completedAt' : IDL.Int,
    'completionDate' : IDL.Text,
    'taskId' : IDL.Text,
  });
  const MonthlyTaskStats = IDL.Record({
    'completedDays' : IDL.Nat,
    'taskTitle' : IDL.Text,
    'totalDays' : IDL.Nat,
    'taskId' : IDL.Text,
  });
  const StreakInfo = IDL.Record({
    'longestStreak' : IDL.Nat,
    'currentStreak' : IDL.Nat,
  });
  const WeeklyStats = IDL.Record({
    'total' : IDL.Nat,
    'date' : IDL.Text,
    'completed' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createTask' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Variant({
            'Weekly' : IDL.Null,
            'Daily' : IDL.Null,
            'Custom' : IDL.Null,
          }),
          IDL.Vec(IDL.Nat),
          IDL.Nat,
          IDL.Text,
          IDL.Opt(IDL.Text),
        ],
        [Task],
        [],
      ),
    'deleteTask' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCompletionsForDate' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(TaskCompletion)],
        ['query'],
      ),
    'getCompletionsForRange' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(TaskCompletion)],
        ['query'],
      ),
    'getMonthlyTaskStats' : IDL.Func(
        [],
        [IDL.Vec(MonthlyTaskStats)],
        ['query'],
      ),
    'getStreakInfo' : IDL.Func([], [StreakInfo], ['query']),
    'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getTasksForDate' : IDL.Func([IDL.Text], [IDL.Vec(Task)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWeeklyStats' : IDL.Func([], [IDL.Vec(WeeklyStats)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markTaskComplete' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : TaskCompletion, 'err' : IDL.Text })],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'unmarkTaskComplete' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'updateTask' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Variant({
            'Weekly' : IDL.Null,
            'Daily' : IDL.Null,
            'Custom' : IDL.Null,
          }),
          IDL.Vec(IDL.Nat),
          IDL.Nat,
          IDL.Text,
          IDL.Opt(IDL.Text),
        ],
        [IDL.Variant({ 'ok' : Task, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };